spring:
  application:
    name: auth-server
  profiles:
    default: ${PROFILE:default}
  config:
    import: "optional:configserver:${CONFIG_URL:http://localhost:7777}"
  datasource:
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
    password: ${db.password}
    username: ${db.username}
    url: ${db.url}
    driver-class-name: ${db.driver}
  jpa:
    show-sql: ${db.show-sql}
    database-platform: ${db.platform}
springdoc:
  swagger-ui:
    operationsSorter: method
    syntaxHighlight:
      theme: monokai
    path: /swagger-ui.html
    filter: 'true'
    tagsSorter: alpha
    tryItOutEnabled: 'true'
  api-docs:
    path: /api-docs
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
server:
  servlet:
    context-path: /auth-server
  port: 3030

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
