apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    app: gateway
    part-of: herowatch

data:
  PROFILE: "oauth2"
  SERVER_PORT: "4040"
  JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0 -XX:MinRAMPercentage=25.0"
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  # When running in cluster, discover the registry-server by service name
  HEROES_MS_URI: "http://heroes-ms"
  AUTH_VALIDATE_URI: "http://auth-server"
