apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: heroWatch/gateway:v4
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4040
          env:
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: PROFILE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: SERVER_PORT
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: JAVA_OPTS
            - name: HEROES-MS-URI
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: HEROES-MS-URI
            - name: AUTH_VALIDATE_URI
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: AUTH_VALIDATE_URI
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
