spring:
  profiles:
    default: oauth2
  application:
    name: gateway
server:
  port: 4040
gateway:
  auth:
    auth-server-uri: ${AUTH_VALIDATE_URI:http://localhost:3030/auth-server/auth/jwt}
  services:
    heroes-ms-uri: ${HEROES_MS_URI:http://localhost:8080}
