spring:
  profiles:
    default: oauth2
  application:
    name: gateway
server:
  port: 4040
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true
