services:
  db_users:
      image: postgres:16.1
      container_name: db-users
      restart: always
      volumes:
        - ./sql/create_schema_users.sql:/docker-entrypoint-initdb.d/create_schema_users.sql
        - ./sql/data_users.sql:/docker-entrypoint-initdb.d/data_users.sql
      environment:
        POSTGRES_DB: 'users-gha'
        POSTGRES_USER: 'admin-gha'
        POSTGRES_PASSWORD: 'adminGHA20181209'
      ports:
        - '9876:5432'
  db_heroes:
      image: postgres:16.1
      container_name: db-heroes
      restart: always
      volumes:
        - ./sql/create_schema_heroes.sql:/docker-entrypoint-initdb.d/create_schema_heroes.sql
        - ./sql/data_heroes.sql:/docker-entrypoint-initdb.d/data_heroes.sql
      environment:
        POSTGRES_DB: 'heroes-gha'
        POSTGRES_USER: 'admin-gha'
        POSTGRES_PASSWORD: 'adminGHA20181209'
      ports:
        - '5432:5432'