services:
  db_users:
      image: postgres:16.1
      container_name: db-users
      restart: always
      volumes:
        - ./sql/create_schema_users.sql:/docker-entrypoint-initdb.d/create_schema_users.sql
        - ./sql/data_users.sql:/docker-entrypoint-initdb.d/data_users.sql
      environment:
        POSTGRES_DB: 'users-gha'
        POSTGRES_USER: 'admin-gha'
        POSTGRES_PASSWORD: 'adminGHA20181209'
      ports:
        - '9876:5432'
  db_heroes:
      image: postgres:16.1
      container_name: db-heroes
      restart: always
      volumes:
        - ./sql/create_schema_heroes.sql:/docker-entrypoint-initdb.d/create_schema_heroes.sql
        - ./sql/data_heroes.sql:/docker-entrypoint-initdb.d/data_heroes.sql
      environment:
        POSTGRES_DB: 'heroes-gha'
        POSTGRES_USER: 'admin-gha'
        POSTGRES_PASSWORD: 'adminGHA20181209'
      ports:
        - '5432:5432'
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    container_name: load-balancer
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.4.3
    container_name: msg-broker
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://msg-broker:9092,PLAINTEXT_INTERNAL://msg-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  