db:
  connection-timeout: 20000
  maximum-pool-size: 5
  password: adminGHA20181209
  driver: org.postgresql.Driver
  username: admin-gha
  url: jdbc:postgresql://db_users:5432/usersc
  show-sql: 'true'
  platform: org.hibernate.dialect.PostgreSQLDialect
application:
  jwt:
    secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9