apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa-patch.yaml

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: ghcr.io/example/heroes-ms
    newTag: 1.0.0
