apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes-ms
  labels:
    app.kubernetes.io/name: heroes-ms
    app.kubernetes.io/part-of: herowatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: heroes-ms
  template:
    metadata:
      labels:
        app.kubernetes.io/name: heroes-ms
        app.kubernetes.io/part-of: herowatch
    spec:
      containers:
        - name: heroes-ms
          image: heroWatch/heroes-ms:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: heroes-ms-config
            - secretRef:
                name: heroes-ms-secrets
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
