apiVersion: v1
kind: Service
metadata:
  name: heroes-ms
  labels:
    app.kubernetes.io/name: heroes-ms
    app.kubernetes.io/part-of: herowatch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: heroes-ms
  ports:
    - name: http
      port: 80
      targetPort: 8080
