apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-server-config
data:
  # Overrides for dev environment
  PROFILE: "default"
  SERVER_PORT: "3030"
  # In-cluster service URLs for dev
  EUREKA_URL: "http://registry-server:8761/eureka"
  CONFIG_URL: "http://config-server:7777"
