spring:
  application:
    name: heroes
  profiles:
    default: ${PROFILE:default}
  config:
    import: "optional:configserver:${CONFIG_URL:http://localhost:7777}"
  datasource:
    hikari:
      connection-timeout: ${db.connection-timeout}
      maximum-pool-size: ${db.maximum-pool-size}
    password: ${db.password}
    username: ${db.username}
    url: ${db.url}
    driver-class-name: ${db.driver}
  jpa:
    show-sql: ${db.show-sql}
    database-platform: ${db.platform}
springdoc:
  swagger-ui:
    operationsSorter: method
    syntaxHighlight:
      theme: monokai
    path: /swagger-ui.html
    filter: 'true'
    tagsSorter: alpha
    tryItOutEnabled: 'true'
  api-docs:
    path: /api-docs
server:
  servlet:
    context-path: /heroes
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: env, health, info

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
