spring:
  application:
    name: heroes-ms
  profiles:
    default: ${PROFILE:default}
  datasource:
    hikari:
      maximum-pool-size: ${DB_MAXIMUN_POOL_SIZE:5}
      connection-timeout: ${DB_CONNECTION_TIME_OUT:20000}
    password: ENC(${DB_PASSWORD:e9D9H5TC8CyjVIDNc6yX2ggOw4tj/HB+he26s7cSsa3+XFVWQcw0HynQTyU=})
    username: ENC(${DB_USERNAME:9KhabgYtaneboQDOuyWs4koh4mpMDthYQZa9O60Qhnj/Mel+DQ==})
    url: ${DB_URL:jdbc:postgresql://localhost:5432/heroes-gha}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    show-sql: ${DB_SHOW_SQL:true}
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
  cloud:
    stream:
      bindings:
        heroes-out-0:
          destination: heroes
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
springdoc:
  swagger-ui:
    operationsSorter: method
    syntaxHighlight:
      theme: monokai
    path: /swagger-ui.html
    filter: 'true'
    tagsSorter: alpha
    tryItOutEnabled: 'true'
  api-docs:
    path: /api-docs
server:
  servlet:
    context-path: /api/v1/heroes-ms
  port: 8080
gha:
  crypto:
    aesKey: ${AES_KEY:kZ6F1Zy0ZQ4n0t9J2wE2R+q+f0nGmJ0r1Yx7G2kLw6A=}
management:
  endpoints:
    web:
      exposure:
        include: health, info
