apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  # Override anything needed for dev
  PROFILE: "oauth2"
  SERVER_PORT: "4040"
  # For a local kind/minikube with in-cluster registry-server service name
  EUREKA_URL: "http://registry-server:8761/eureka"
