spring:
  profiles:
    active: default
    #active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        #native:
          #search-locations: file:./config
        git:
          uri: https://github.com/miguelshevchuk/HeroWatch.git
          search-paths: config
          default-label: main
          clone-on-start: true
server:
  port: 7777
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
