apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-server-config
  labels:
    app.kubernetes.io/name: auth-server
    app.kubernetes.io/part-of: herowatch

data:
  PROFILE: "default"
  SERVER_PORT: "3030"
  JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0 -XX:MinRAMPercentage=25.0"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  DB_MAXIMUN_POOL_SIZE: "5"
  DB_CONNECTION_TIME_OUT: "20000"
  DB_URL: "jdbc:postgresql://host.docker.internal:9876/users-gha"
  DB_DRIVER: "org.postgresql.Driver"
  DB_SHOW_SQL: "true"
  DB_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"

