apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app.kubernetes.io/name: auth-server
    app.kubernetes.io/part-of: herowatch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-server
  ports:
    - name: http
      port: 80
      targetPort: 3030
